### ISSUE TITLE
Compile error : A coroutine cannot have a return type containing 'auto'

### ISSUE THREAD

**Issue by ameaninglessname** [landelare/ue5coro#12]
> Using Visual Studio 2022 14.35.32217 toolchain (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215) and Windows 10.0.22621.0 SDK (C:\Program Files (x86)\Windows Kits\10).

> Error C7617 : 'SetupPlayerInputComponent::<lambda_4>::operator ()': A coroutine cannot have a return type containing 'auto'

> [C7617] Please use '/await' command-line option to enable relevant extensions

I got this error when trying to capture variable in the coroutine lambda:

```C++
auto LoadingLambda = []
{
    auto Coroutine = [WeakThis = FWeakObjectPtr{this}] -> UE5Coro::TCoroutine<>
    {
        // co_await something

        // validate WeakThis

        co_return;
    };
    Coroutine();
};
```

After changing it to this, it compiles fine:
```C++
auto LoadingLambda = []
{
    auto Coroutine = [this] -> UE5Coro::TCoroutine<>
    {
        FWeakObjectPtr WeakThis{this};

        // co_await something

        // validate WeakThis

        co_return;
    };
    Coroutine();
};
```

but still get a warning from rider:
![image](https://user-images.githubusercontent.com/20263103/233153501-922566b6-8e3d-4a40-8232-208d67e13014.png)

**Comment by landelare** [comment]
Your code has multiple errors. You're trying to capture `[this]` from within a nested lambda that's already "lost" `this` due to LoadingLambda having no captures, and the mandatory `()` is missing before the `->` return type specification. With these issues fixed, I managed to compile a similar nested lambda setup on both MSVC and Clang.

I can't do anything about Rider's tooltips, try reporting this issue to them.
